Repository Sticky-Seacher/sticky-searcher-extension, pull requests merged in 2025-01, with the labels that each got.

#1 [환경구축] 보일러플레이트 설정
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  .gitignore
  .husky/pre-commit
  .node-version
  .nvmrc
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/manifest.json
  public/service-worker.js
  public/sticky-seacher-logo.png
  src/App.css
  src/App.jsx
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
Labels: chore

#2 [환경구축] 보일러플레이트 설정 (#1)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  .gitignore
  .husky/pre-commit
  .node-version
  .nvmrc
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/manifest.json
  public/service-worker.js
  public/sticky-seacher-logo.png
  src/App.css
  src/App.jsx
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
Labels: chore

#9 feat: 하이라이팅될 타겟 요소를 찾는 로직 구현
  src/getLeafTargetElements.js
Labels: feat, review

#15 feat: description 데이터 추출 로직 구현
  src/getDescription.js
Labels: feat, review

#13 feat: 검색쿼리 키워드 취득 로직 구현
  src/getSearchKeywords.js
Labels: feat, review

#17 feat: 하이라이팅 적용 로직 구현
  src/highlight.js
Labels: feat, review

#20 feat: 사이드 패널 구축
  background/background.js
  content-script/content.js
  content-script/getBodyString.js
  content-script/getDescription.js
  content-script/getLeafTargetElements.js
  content-script/getSearchKeywords.js
  package.json
  public/manifest.json
  vite-background.config.js
  vite-content.config.js
Labels: feat, review

#18 feat: 공통 컴포넌트 UI 구현
  public/history_icon.png
  public/page_Icon.png
  public/search_icon.png
  src/App.jsx
  src/components/history-section/index.jsx
  src/components/lately-history-croup/LatelyHistoryGroup.jsx
  src/components/search-section/KetwordGroup.jsx
  src/components/search-section/SearchSectionInput.jsx
  src/components/search-section/index.jsx
  src/components/shared/IconButton.jsx
  src/components/shared/TextButton.jsx
Labels: feat, review

#21 fix: 중간점검을 위한 코드 통합
  content-script/content.js
  content-script/getDescription.js
  content-script/highlight.js
  src/App.jsx
  src/components/lately-history-croup/LatelyHistoryGroup.jsx
  src/components/search-section/SearchSectionInput.jsx
Labels: fix

#23 feat: DB 구축
  .gitignore
  package-lock.json
  package.json
  src/firebase-collection.js
  src/firebase-handler.js
  src/firebase.js
Labels: feat, D+1

#25 feat: 검색 페이지 로드 시 linkMap 생성 및 저장
  background/background.js
  content-script/content.js
  content-script/linkMap.js
  content-script/mapToJosn.js
  eslint.config.js
  public/manifest.json
Labels: feat, D+1

#27 feat: 로그인 기능
  background/background.js
  eslint.config.js
  public/manifest.json
  src/components/shared/IconButton.jsx
  src/firebase/firebase-collection.js
  src/firebase/firebase-handler.js
  src/firebase/firebase.js
Labels: feat, D-0

#29 feat: 스크롤 구현
  background/background.js
  background/convertToLinkMap.js
  background/createRules.js
  content-script/content.js
  content-script/highlight.js
  package-lock.json
  public/manifest.json
  src/components/search-section/SearchSectionInput.jsx
  src/components/search-section/index.jsx
  src/components/shared/TextButton.jsx
Labels: feat, D-0

#31 fix: merge conflict
  background/background.js
  eslint.config.js
  public/manifest.json
  src/components/shared/IconButton.jsx
  src/components/shared/TextButton.jsx
Labels: fix, D-0

#33 fix: firebase CRUD 보완
  src/firebase/CRUD.js
  src/firebase/firebase-collection.js
  src/firebase/firebase-handler.js
Labels: fix, D-0

#34 feat: history section 구현
  src/components/history-section/index.jsx
  src/components/shared/IconButton.jsx
  src/firebase/CRUD.js
Labels: feat, D-0

#38 feat: lately history section 구현
  src/components/history-section/index.jsx
  src/components/lately-history-croup/LatelyHistoryGroup.jsx
  src/components/shared/HistoryItem.jsx
  src/firebase/CRUD.js
Labels: feat, D-0

#40 feat: search section 내 토글 구현
  content-script/content.js
  content-script/highlight.js
  content-script/toggle.js
  public/page_Icon.png
  src/App.jsx
  src/components/search-section/KeywordGroup.jsx
  src/components/search-section/ToggleableKeywordButton.jsx
  src/components/search-section/index.jsx
  src/components/shared/TextButton.jsx
Labels: feat, D-0

#43 fix: history 저장 관련 mock data에서 real data로 변경
  src/components/history-section/index.jsx
  src/components/shared/HistoryItem.jsx
Labels: fix, D-0

#44 chore: daisyUI 추가
  package-lock.json
  package.json
  tailwind.config.js
Labels: chore, D-0

#46 feat: firestore연동을 위해 user 스키마 설정 후 history 추가 기능
  src/firebase/history.js
  src/firebase/user.js
Labels: feat, D+1

#48 feat: webSite auth Data + extension auth Data 연동 기능
  content-script/content.js
  public/manifest.json
  src/App.jsx
  src/components/history-section/index.jsx
Labels: feat, D+1

#50 feat: webSite + extension auth identification 후 로그인 페이지 이동
  background/background.js
  content-script/content.js
  public/manifest.json
  src/App.jsx
  src/components/history-section/index.jsx
  src/context/UserInfo.jsx
Labels: feat, D-0
