Repository Sticky-Seacher/sticky-searcher-extension, pull requests merged in 2025-03, with the labels that each got.

#55 chore: 배포 준비
  background/background.js
  public/manifest.json
Labels: chore

#56 chore: 도메인 변경
  src/components/history-section/index.jsx
Labels: chore, D-0

#57 refactor: 불필요 권한 삭제
  public/manifest.json
Labels: refactor
